#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/opt/platform_paas_staging}"
ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/.env.staging}"
SERVICE_NAME="${SERVICE_NAME:-platform-paas-backend-staging}"
EXPECTED_APP_ENV="${EXPECTED_APP_ENV:-staging}"
RUN_REMOTE_BACKEND_SMOKE_POST_DEPLOY="${RUN_REMOTE_BACKEND_SMOKE_POST_DEPLOY:-true}"
REMOTE_BACKEND_SMOKE_BASE_URL="${REMOTE_BACKEND_SMOKE_BASE_URL:-http://127.0.0.1:8200}"
REMOTE_BACKEND_SMOKE_TARGET="${REMOTE_BACKEND_SMOKE_TARGET:-base}"
REMOTE_BACKEND_SMOKE_STRICT="${REMOTE_BACKEND_SMOKE_STRICT:-true}"

export PROJECT_ROOT
export ENV_FILE
export SERVICE_NAME
export EXPECTED_APP_ENV
export RUN_REMOTE_BACKEND_SMOKE_POST_DEPLOY
export REMOTE_BACKEND_SMOKE_BASE_URL
export REMOTE_BACKEND_SMOKE_TARGET
export REMOTE_BACKEND_SMOKE_STRICT

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "$SCRIPT_DIR/deploy_backend.sh"
